name: Deploy to Deno Deploy

on:
    push:
        # Change if using a different production branch
        branches: [ main ]
        pull_request:
            branches: [ main ]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

steps:
    - name: Clone repository
    uses: actions/checkout@v3

- name: Setup Deno
uses: denoland/setup-deno@v1.1.0

- name: Build site
# Change if using non-default input/output directories
run: deno run -A --unstable https://deno.land/x/ter/main.ts --input ./wiki

- name: Deploy to Deno Deploy
uses: denoland/deployctl@v1
with:
    # Replace with the project name on Deno Deploy
    project: wiki
    entrypoint: https://deno.land/std/http/file_server.ts
    # Change if using non-default output directory
    root: _site